package br.com.zapiti.translateexpression.utils

import java.util.*

object TypeLanguageUtils {
    fun getLanguagens(): ArrayList<Language> {
        return arrayListOf(
            Language.AUTO_DETECT,
            Language.AFRIKAANS,
            Language.ALBANIAN,
            Language.ARABIC,
            Language.ARMENIAN,
            Language.AZERBAIJANI,
            Language.BASQUE,
            Language.BELARUSIAN,
            Language.BENGALI,
            Language.BULGARIAN,
            Language.CATALAN,
            Language.CHINESE,
            Language.CROATIAN,
            Language.CZECH,
            Language.DANISH,
            Language.DUTCH,
            Language.ENGLISH,
            Language.ESTONIAN,
            Language.FILIPINO,
            Language.FINNISH,
            Language.FRENCH,
            Language.GALICIAN,
            Language.GEORGIAN,
            Language.GERMAN,
            Language.GREEK,
            Language.GUJARATI,
            Language.HAITIAN_CREOLE,
            Language.HEBREW,
            Language.HINDI,
            Language.HUNGARIAN,
            Language.ICELANDIC,
            Language.INDONESIAN,
            Language.IRISH,
            Language.ITALIAN,
            Language.JAPANESE,
            Language.KANNADA,
            Language.KOREAN,
            Language.LATIN,
            Language.LATVIAN,
            Language.LITHUANIAN,
            Language.MACEDONIAN,
            Language.MALAY,
            Language.MALTESE,
            Language.NORWEGIAN,
            Language.PERSIAN,
            Language.POLISH,
            Language.PORTUGUESE,
            Language.ROMANIAN,
            Language.RUSSIAN,
            Language.SERBIAN,
            Language.SLOVAK,
            Language.SLOVENIAN,
            Language.SPANISH,
            Language.SWAHILI,
            Language.SWEDISH,
            Language.TAMIL,
            Language.TELUGU,
            Language.THAI,
            Language.TURKISH,
            Language.UKRAINIAN,
            Language.URDU,
            Language.VIETNAMESE,
            Language.WELSH,
            Language.YIDDISH,
            Language.CHINESE_SIMPLIFIED,
            Language.CHINESE_TRADITIONAL
        )
    }
}